### ISSUE TITLE
Extract UAC timer class

### ISSUE THREAD

**Issue by michaellperry** [Jay-Rad/InstaTech_Client#2]
Here's a nice simple extraction you can try, if you are up for it. The StartUACTimer function is the only one that uses the UacTimer field. It depends upon the handleUAC field, which is set in menuUAC_Click. This means that the UacTimer and handleUAC fields want to be encapsulated with StartUACTimer.

You can create a new class and move the UacTimer, handleUAC, and StartUACTimer into it. Replace the two fields with an instance of this class, and modify the call to StartUACTimer to call the new instance. In order to set the handleUAC field from the main window, turn this into a property.

I have a branch with these changes in it, but I figured I would give you a chance to try it.

By the way, these kinds of changes are called "refactorings". It's just like when you do algebra to change the form of an equation without changing what it means. These are changes to code that don't change its behavior. And they are just as mechanical. It's a great way to gradually improve the structure of your code.

**Comment by bitbound** [comment]
InstaTech, Adit, and DoXM have been discontinued.  All future work will be done in the Remotely project.

https://github.com/jay-rad/remotely
